services:
  olivet_watcher_app:
    image: pypeaday/vocal-remover-watcher
    container_name: olivet-youtube-watcher
    volumes:
      - /tank/encrypted/docker/pinchflat/downloads:/input:ro
      - /tank/encrypted/docker/vocal_remover_app/watcher-app/processed_mp3s:/output # Mount OUTPUT_DIR from the host
      - /tank/encrypted/docker/vocal_remover_app/watcher-app/db:/data
    working_dir: /app
    environment:
      - WATCH_DIR=/input/Olivet Bible - Under Review
      - OUTPUT_DIR=/output
      - DB_PATH=/data/processed_files.db
    restart: unless-stopped

