name: Build Watcher App
on:
  workflow_dispatch:
  push:
    branches:
      # TODO: using my branch - might be worth cleaning up
      - nic
  #     - 'feature/*'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      registry: docker.io
      targetRepo: pypeaday/vocal-remover-watcher

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: watcher.Dockerfile
          push: true
          tags: ${{ env.registry }}/${{ env.targetRepo }}:latest
